"""empty message

Revision ID: 2c5c6f0b1227
Revises: aba6a3e14190
Create Date: 2022-04-23 21:04:27.629695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5c6f0b1227'
down_revision = 'aba6a3e14190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_wordlist',
    sa.Column('id', sa.Integer(), nullable=False, comment='敏感词ID'),
    sa.Column('wordname', sa.String(length=255), nullable=True, comment='敏感词名称'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='是否启用'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_wordlist_wordkinds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='标识'),
    sa.Column('wordlist_id', sa.Integer(), nullable=True, comment='敏感词ID'),
    sa.Column('wordkinds_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.ForeignKeyConstraint(['wordkinds_id'], ['admin_wordkinds.id'], ),
    sa.ForeignKeyConstraint(['wordlist_id'], ['admin_wordlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_wordlist_wordkinds')
    op.drop_table('admin_wordlist')
    # ### end Alembic commands ###
