"""empty message

Revision ID: 5e506c68e805
Revises: aba6a3e14190
Create Date: 2022-04-12 14:07:22.456926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e506c68e805'
down_revision = 'aba6a3e14190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_wordkinds', sa.Column('kindid', sa.Integer(), nullable=False, comment='敏感词分类ID'))
    op.drop_column('admin_wordkinds', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_wordkinds', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='敏感词分类ID'))
    op.drop_column('admin_wordkinds', 'kindid')
    # ### end Alembic commands ###
