"""empty message

Revision ID: aba6a3e14190
Revises: 
Create Date: 2022-04-12 13:00:13.760900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba6a3e14190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_wordkinds',
    sa.Column('id', sa.Integer(), nullable=False, comment='敏感词分类ID'),
    sa.Column('kindname', sa.String(length=255), nullable=True, comment='分类名称'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='是否启用'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('admin_role_power_ibfk_1', 'admin_role_power', type_='foreignkey')
    op.drop_constraint('admin_role_power_ibfk_2', 'admin_role_power', type_='foreignkey')
    op.create_foreign_key(None, 'admin_role_power', 'admin_power', ['power_id'], ['id'])
    op.create_foreign_key(None, 'admin_role_power', 'admin_role', ['role_id'], ['id'])
    op.drop_constraint('admin_user_role_ibfk_2', 'admin_user_role', type_='foreignkey')
    op.drop_constraint('admin_user_role_ibfk_1', 'admin_user_role', type_='foreignkey')
    op.create_foreign_key(None, 'admin_user_role', 'admin_role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'admin_user_role', 'admin_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_user_role', type_='foreignkey')
    op.drop_constraint(None, 'admin_user_role', type_='foreignkey')
    op.create_foreign_key('admin_user_role_ibfk_1', 'admin_user_role', 'admin_role', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('admin_user_role_ibfk_2', 'admin_user_role', 'admin_user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'admin_role_power', type_='foreignkey')
    op.drop_constraint(None, 'admin_role_power', type_='foreignkey')
    op.create_foreign_key('admin_role_power_ibfk_2', 'admin_role_power', 'admin_role', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('admin_role_power_ibfk_1', 'admin_role_power', 'admin_power', ['power_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_table('admin_wordkinds')
    # ### end Alembic commands ###
