"""empty message

Revision ID: c2d24126418b
Revises: 2c5c6f0b1227
Create Date: 2022-04-25 20:20:22.364174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d24126418b'
down_revision = '2c5c6f0b1227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_photo', sa.Column('flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_photo', 'flag')
    # ### end Alembic commands ###
